---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app-d
  namespace: default
  labels:
    app: nodejs-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app-c
          image: "devopshint/node-app:latest"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-svc
  namespace: default
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - name: http
      targetPort: 3000
      port: 80
